/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef EXAMPLEOBJECT_H
#define EXAMPLEOBJECT_H

/* function declarations */
void init_exampleObject(void);
Netsnmp_Node_Handler handle_exampleObject1;
Netsnmp_Node_Handler handle_exampleObject2;
Netsnmp_Node_Handler handle_exampleObject3;
Netsnmp_Node_Handler handle_exampleObject4;

#endif /* EXAMPLEOBJECT_H */
