/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef EXAMPLENOTIFICATIONS_H
#define EXAMPLENOTIFICATIONS_H

/* function declarations */
int send_exampleNotify1_trap(void);

#endif /* EXAMPLENOTIFICATIONS_H */
