/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "exampleNotifications.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_exampleNotify1_trap( void )
{
    netsnmp_variable_list  *var_list = NULL;
    const oid exampleNotify1_oid[] = { 1,3,6,1,4,1,9999,1,0,1 };
    const oid exampleNotifyObj1_oid[] = { 1,3,6,1,4,1,9999,10,1, 0 };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        exampleNotify1_oid, sizeof(exampleNotify1_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        exampleNotifyObj1_oid, OID_LENGTH(exampleNotifyObj1_oid),
        ASN_INTEGER,
        /* Set an appropriate value for exampleNotifyObj1 */
        NULL, 0);

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
