/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef EXAMPLEOBJECT_H
#define EXAMPLEOBJECT_H

/* function declarations */
void init_exampleObject(void);
void initialize_table_simpleTable(void);
Netsnmp_Node_Handler simpleTable_handler;
Netsnmp_First_Data_Point  simpleTable_get_first_data_point;
Netsnmp_Next_Data_Point   simpleTable_get_next_data_point;
NetsnmpCacheLoad simpleTable_load;
NetsnmpCacheFree simpleTable_free;
#define SIMPLETABLE_TIMEOUT  60
void initialize_table_generalTable(void);
Netsnmp_Node_Handler generalTable_handler;
Netsnmp_First_Data_Point  generalTable_get_first_data_point;
Netsnmp_Next_Data_Point   generalTable_get_next_data_point;
NetsnmpCacheLoad generalTable_load;
NetsnmpCacheFree generalTable_free;
#define GENERALTABLE_TIMEOUT  60

/* column number definitions for table simpleTable */
       #define COLUMN_SIMPLETBCOLUM1		1
       #define COLUMN_SIMPLETBCOLUM2		2

/* column number definitions for table generalTable */
       #define COLUMN_GENERALTBCOLUM1		1
       #define COLUMN_GENERALTBCOLUM2		2
       #define COLUMN_GENERALTBCOLUM3		3
       #define COLUMN_GENERALTBCOLUM4		4
#endif /* EXAMPLEOBJECT_H */
