/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef EXAMPLEOBJECT_H
#define EXAMPLEOBJECT_H

/* function declarations */
void init_exampleObject(void);

#endif /* EXAMPLEOBJECT_H */
