/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

/********************************************************************
 *                       NOTE   NOTE   NOTE
 *   This file is auto-generated and SHOULD NOT BE EDITED by hand.
 *   Modify the exampleObject_checkfns_local.[ch] files insead so that you
 *   can regenerate this one as mib2c improvements are made.
 ********************************************************************/

/* standard headers */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include "exampleObject_checkfns.h"
#include "exampleObject_checkfns_local.h"
#include "exampleObject_enums.h"

/** Decides if an incoming value for the simpleTbColum2 mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_simpleTbColum2(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

	ret = SNMP_ERR_NOERROR;


    /** looks ok, call the local version of the same function. */
      return check_simpleTbColum2_local(type, val, val_len, old_val, old_val_len);
    }
/** Decides if an incoming value for the generalTbColum3 mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_generalTbColum3(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;

    /** Check the ranges of the passed value for legality */
	    if (
	       !(val_len >= 0 && val_len <= 255)
            ) {
            return SNMP_ERR_WRONGVALUE;
            }


    /** looks ok, call the local version of the same function. */
      return check_generalTbColum3_local(type, val, val_len, old_val, old_val_len);
    }
/** Decides if an incoming value for the generalTbColum4 mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_generalTbColum4(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

	ret = SNMP_ERR_NOERROR;


    /** looks ok, call the local version of the same function. */
      return check_generalTbColum4_local(type, val, val_len, old_val, old_val_len);
    }
