/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

/* standard headers */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include "exampleObject_checkfns.h"
#include "exampleObject_enums.h"

/** Decides if an incoming value for the simpleTbColum2 mib node is legal, from a local implementation specific viewpoint.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_simpleTbColum2_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len) {

    /** XXX: you may want to check aspects of the new value that
       were not covered by the automatic checks by the parent function. */

    /** XXX: you make want to check that the requested change from
        the old value to the new value is legal (ie, the transistion
        from one value to another is legal */
      
    /** if everything looks ok, return SNMP_ERR_NOERROR */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the generalTbColum3 mib node is legal, from a local implementation specific viewpoint.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_generalTbColum3_local(int type, char *val, size_t val_len, char *old_val, size_t old_val_len) {

    /** XXX: you may want to check aspects of the new value that
       were not covered by the automatic checks by the parent function. */

    /** XXX: you make want to check that the requested change from
        the old value to the new value is legal (ie, the transistion
        from one value to another is legal */
      
    /** if everything looks ok, return SNMP_ERR_NOERROR */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the generalTbColum4 mib node is legal, from a local implementation specific viewpoint.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_generalTbColum4_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len) {

    /** XXX: you may want to check aspects of the new value that
       were not covered by the automatic checks by the parent function. */

    /** XXX: you make want to check that the requested change from
        the old value to the new value is legal (ie, the transistion
        from one value to another is legal */
      
    /** if everything looks ok, return SNMP_ERR_NOERROR */
      return SNMP_ERR_NOERROR;
    }
