/*
 * Note: this file originally auto-generated by mib2c using
 *        : $
 * 
 */
#ifndef EXAMPLEOBJECT_CHECKFNS_H
#define EXAMPLEOBJECT_CHECKFNS_H

/* these functions are designed to check incoming values for 
columns in the simpleTable table for legality with respect to 
datatype and value according to local conventions.  You should modify
them as appropriate.  They will be called from parent check_value
functions that are auto-generated using mib2c and the parent functions
should NOT be modified.
 */

    int check_simpleTbColum2_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for 
columns in the generalTable table for legality with respect to 
datatype and value according to local conventions.  You should modify
them as appropriate.  They will be called from parent check_value
functions that are auto-generated using mib2c and the parent functions
should NOT be modified.
 */

    int check_generalTbColum3_local(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
    int check_generalTbColum4_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);

#endif /* EXAMPLEOBJECT_CHECKFNS_H */

