/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef EXAMPLEOBJECT_H
#define EXAMPLEOBJECT_H

/** other required module components */
config_require(exampleObject_access)
config_require(exampleObject_checkfns)

/* function declarations */
void init_exampleObject(void);
void initialize_table_simpleTable(void);
Netsnmp_Node_Handler simpleTable_handler;

void initialize_table_generalTable(void);
Netsnmp_Node_Handler generalTable_handler;


/* column number definitions for table simpleTable */
#include "exampleObject_columns.h"

/* enum definions */
#include "exampleObject_enums.h"


/* column number definitions for table generalTable */
#include "exampleObject_columns.h"

/* enum definions */
#include "exampleObject_enums.h"

#endif /** EXAMPLEOBJECT_H */
