/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.6 2003/02/20 00:52:07 hardaker Exp $
 */

/***********************************************************************
 *   This file is auto-generated and SHOULD NOT BE EDITED by hand.
 *   Modify the exampleObject_checkfns_local.[ch] files insead.
 *   (so that you can regenerate this one as mib2c improvements are made)
 ***********************************************************************/
#ifndef EXAMPLEOBJECT_CHECKFNS_H
#define EXAMPLEOBJECT_CHECKFNS_H

/** make sure we load the functions that you can modify */
config_require(exampleObject_checkfns_local)

/* these functions are designed to check incoming values for 
columns in the simpleTable table for legality with respect to 
datatype and value.
 */

      int check_simpleTbColum2(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for 
columns in the generalTable table for legality with respect to 
datatype and value.
 */

      int check_generalTbColum3(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_generalTbColum4(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);

#endif /* EXAMPLEOBJECT_CHECKFNS_H */

