/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef EXAMPLEOBJECT_ACCESS_H
#define EXAMPLEOBJECT_ACCESS_H

/** User-defined data access functions for data in table simpleTable */
/** row level accessors */
Netsnmp_First_Data_Point  simpleTable_get_first_data_point;
Netsnmp_Next_Data_Point   simpleTable_get_next_data_point;
int simpleTable_commit_row(void **my_data_context, int new_or_del);
void * simpleTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      long *get_simpleTbColum1(void *data_context, size_t *ret_len);
      long *get_simpleTbColum2(void *data_context, size_t *ret_len);
      int set_simpleTbColum2(void *data_context, long *val, size_t val_len);
/** User-defined data access functions for data in table generalTable */
/** row level accessors */
Netsnmp_First_Data_Point  generalTable_get_first_data_point;
Netsnmp_Next_Data_Point   generalTable_get_next_data_point;
int generalTable_commit_row(void **my_data_context, int new_or_del);
void * generalTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      u_long *get_generalTbColum1(void *data_context, size_t *ret_len);
      u_long *get_generalTbColum2(void *data_context, size_t *ret_len);
      char *get_generalTbColum3(void *data_context, size_t *ret_len);
      int set_generalTbColum3(void *data_context, char *val, size_t val_len);
      long *get_generalTbColum4(void *data_context, size_t *ret_len);
      int set_generalTbColum4(void *data_context, long *val, size_t val_len);

#endif /* EXAMPLEOBJECT_ACCESS_H */
