/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef EXAMPLEOBJECT_COLUMNS_H
#define EXAMPLEOBJECT_COLUMNS_H

/* column number definitions for table simpleTable */
       #define COLUMN_SIMPLETBCOLUM1		1
       #define COLUMN_SIMPLETBCOLUM2		2

/* column number definitions for table generalTable */
       #define COLUMN_GENERALTBCOLUM1		1
       #define COLUMN_GENERALTBCOLUM2		2
       #define COLUMN_GENERALTBCOLUM3		3
       #define COLUMN_GENERALTBCOLUM4		4
#endif /* EXAMPLEOBJECT_COLUMNS_H */
