/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef EXAMPLEOBJECT_H
#define EXAMPLEOBJECT_H

/* function declarations */
void init_exampleObject(void);
FindVarMethod var_exampleObject;
FindVarMethod var_simpleTable;
FindVarMethod var_generalTable;
WriteMethod write_exampleObject2;
WriteMethod write_exampleObject3;
WriteMethod write_exampleObject4;
WriteMethod write_simpleTbColum2;
WriteMethod write_generalTbColum3;
WriteMethod write_generalTbColum4;

#endif /* EXAMPLEOBJECT_H */
