/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef A_H
#define A_H

/* function declarations */
void init_a(void);
Netsnmp_Node_Handler handle_test;

#endif /* A_H */
